woody_discourse_yaml_src: templates/discourse/discourse.yml.j2
woody_discourse_container_path: '{{ common_docker_compose_directory }}/discourse'
woody_discourse_backup_dir: '{{ common_docker_compose_data_dir }}/discourse/backups/'
woody_discourse_container_name: discourse

woody_gitlab_container_name: solero-gitlab
woody_gitlab_backup_dir: '{{ common_docker_compose_data_dir }}/gitlab/backups/'

woody_nginx_container_name: solero-nginx
