- name: ğŸ†™ Update & Upgrade Packages
  tags: [update, packages]
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: ğŸ” Check Reboot Flag
  tags: [reboot, check]
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_update_reboot_required

- name: ğŸ”„ Reboot If Needed
  tags: [reboot]
  ansible.builtin.reboot:
  when: common_update_reboot_required.stat.exists
