common_docker_compose:
  repo: git@github.com:ben-pearce/etch-server-deployment.git
  environment:
    - key: HOST
      value: etch.benpearce.io
    - key: ADMIN_MAIL
      value: me@benpearce.io
    - key: DNS_INTERFACE
      value: 10.0.0.2
    - key: SMTP_HOST
      value: mail.benpearce.io
    - key: SMTP_USER
      value: notifications@benpearce.io
    - key: LAN_SUBNET
      value: 10.0.0.0/24
    - key: ZBX_HOSTNAME
      value: etch
    - key: ZBX_SERVER_HOST
      value: zabbix.benpearce.io
    - key: ZBX_REFRESHACTIVECHECKS
      value: 60
