common_users:
  - uid: 2000
    name: etch
    groups: [docker]
  - uid: 2001
    name: borg
    groups: [docker]
common_users_sudoers:
  - user: borg
    runas: root
    commands: /usr/lib/sftp-server
    nopassword: true
common_users_known_hosts:
  - host: github.com
    user: etch
common_users_ssh_config:
  - user: etch
    remote_user: git
    hostname: github.com
    host: github
    identity_file: /home/etch/.ssh/id_ed25519
common_docker_compose:
  - repo: git@github.com:ben-pearce/etch-server-deployment.git
    user: etch
    environment:
      - key: HOST
        value: etch.benpearce.io
      - key: ADMIN_MAIL
        value: me@benpearce.io
      - key: PUID
        value: 2000
      - key: PGID
        value: 2000
      - key: DNS_INTERFACE
        value: 10.0.0.2
      - key: DATA_DIR
        value: /opt/etch-server-deployment
      - key: SMTP_HOST
        value: mail.benpearce.io
      - key: SMTP_USER
        value: notifications@benpearce.io
      - key: LAN_SUBNET
        value: 10.0.0.0/24
      - key: ZBX_HOSTNAME
        value: etch
      - key: ZBX_SERVER_HOST
        value: zabbix.benpearce.io
      - key: ZBX_REFRESHACTIVECHECKS
        value: 60
