common_docker_compose:
  repo: git@github.com:ben-pearce/jessie-server-deployment.git
  environment:
    - key: HOST
      value: jessie.benpearce.io
    - key: ADMIN_MAIL
      value: me@benpearce.io
    - key: AUTHENTIK_HOST
      value: https://authentik.etch.benpearce.io
    - key: LOG_DIR
      value: /var/log
    - key: LAN_SUBNET
      value: 10.0.0.0/24
    - key: SMTP_HOST
      value: mail.benpearce.io
    - key: SMTP_USER
      value: notifications@benpearce.io
    - key: PRINTER_HOST
      value: printer.benpearce.io
    - key: NFS_HOST
      value: lenny.benpearce.io
    - key: ZBX_HOSTNAME
      value: jessie
    - key: ZBX_SERVER_HOST
      value: zabbix.benpearce.io
    - key: ZBX_REFRESHACTIVECHECKS
      value: 60
