common_users_users:
  - uid: 2000
    name: deploy
    abilities:
      - compose-stack-update
      - mailcow-update
  - uid: 2001
    name: borg
    abilities:
      - mount-filesystem
      - mailcow-backup
  - uid: 2002
    name: git
common_docker_compose:
  repo: git@github.com:ben-pearce/rc-server-deployment.git
  environment:
    - key: ZBX_HOSTNAME
      value: rc
    - key: ZBX_SERVER_HOST
      value: zabbix.benpearce.io
    - key: ZBX_REFRESHACTIVECHECKS
      value: 60
