common_users:
  - uid: 2000
    name: rc
    groups: [docker]
  - uid: 2001
    name: borg
    groups: [docker]
common_users_sudoers:
  - user: borg
    runas: root
    commands: 
      - /usr/lib/sftp-server
      - /home/rc/rc-server-deployment/mailcow/helper-scripts/backup_and_restore.sh
      - /bin/rm -rf /mnt/data/rc-server-deployment/mailcow*
    nopassword: true
    setenv: true
  - user: rc
    runas: root
    commands:
      - /bin/chown -R rc /home/rc/rc-server-deployment/*
      - /home/rc/rc-server-deployment/mailcow/update.sh --force
    nopassword: true
common_users_known_hosts:
  - host: github.com
    user: rc
common_users_ssh_config:
  - user: rc
    remote_user: git
    hostname: github.com
    host: github
    identity_file: /home/rc/.ssh/id_ed25519
common_journald_config:
  - option: Storage
    value: volatile
  - option: Compress
    value: 'yes'
  - option: SystemMaxUse
    value: 50M
  - option: SystemMaxFileSize
    value: 5M
  - option: ForwardToSyslog
    value: 'no'
rc_data_path: /mnt/data/rc-server-deployment
common_docker_compose:
  - repo: git@github.com:ben-pearce/rc-server-deployment.git
    user: rc
    environment:
      - key: PUID
        value: 2000
      - key: PGID
        value: 2000
      - key: DATA_DIR
        value: '{{ rc_data_path }}'
      - key: ZBX_HOSTNAME
        value: rc
      - key: ZBX_SERVER_HOST
        value: zabbix.benpearce.io
      - key: ZBX_REFRESHACTIVECHECKS
        value: 60
