common_users:
  - uid: 2000
    name: sid
    groups: [docker]
  - uid: 2001
    name: borg
    groups: [docker]
common_users_sudoers:
  - user: borg
    runas: root
    commands: /usr/lib/sftp-server
    nopassword: true
common_users_known_hosts:
  - host: github.com
    user: sid
common_users_ssh_config:
  - user: sid
    remote_user: git
    hostname: github.com
    host: github
    identity_file: /home/sid/.ssh/id_ed25519
common_journald_config:
  - option: Storage
    value: volatile
  - option: Compress
    value: 'yes'
  - option: SystemMaxUse
    value: 50M
  - option: SystemMaxFileSize
    value: 5M
  - option: ForwardToSyslog
    value: 'no'
common_docker_compose:
  - repo: git@github.com:ben-pearce/sid-server-deployment.git
    user: sid
    environment:
      - key: HOST
        value: sid.benpearce.io
      - key: TZ
        value: Europe/London
      - key: PUID
        value: 2000
      - key: PGID
        value: 2000
