common_docker_compose:
  repo: git@github.com:ben-pearce/sparks-server-deployment.git
  environment:
    - key: HOST
      value: sparks.benpearce.io
    - key: NPM_HOST_PATTERN
      value: "^[a-z0-9-]+\\.dev\\.sparks\\.benpearce\\.io$"
    - key: AUTHENTIK_HOST
      value: https://authentik.etch.benpearce.io
    - key: ADMIN_MAIL
      value: me@benpearce.io
    - key: PUID
      value: 1000
    - key: PGID
      value: 1000
    - key: HOST_IP
      value: '10.0.0.5'
    - key: SMTP_USER
      value: notifications@benpearce.io
    - key: SMTP_HOST
      value: mail.benpearce.io
    - key: NFS_HOST
      value: lenny.benpearce.io
    - key: ZBX_HOSTNAME
      value: sparks
    - key: ZBX_SERVER_HOST
      value: zabbix.benpearce.io
    - key: ZBX_REFRESHACTIVECHECKS
      value: 60
