common_docker_compose_data_dir: /opt/applications
common_docker_compose:
  repo: git@github.com:ben-pearce/wireguard-server-deployment.git
  environment:
    - key: PEERDNS
      value: 10.0.0.2
    - key: PEERS
      value: GitHub,Ben,ThinkPadP14s,Pixel10ProXL,Yasmin
    - key: SERVERURL
      value: wireguard.benpearce.io
    - key: SERVERPORT
      value: 51450
    - key: DDCLIENT_CLOUDFLARE_ZONE
      value: benpearce.io
