common_users_users:
  - uid: 2000
    name: deploy
    abilities:
      - compose-stack-update
      - discourse-update
  - uid: 2001
    name: borg
    abilities:
      - mount-filesystem
      - discourse-backup
      - gitlab-backup
  - uid: 2002
    name: git
common_docker_compose:
  repo: git@github.com:ben-pearce/woody-server-deployment.git
  environment:
    - key: HOST
      value: solero.me
    - key: ZBX_HOSTNAME
      value: woody
    - key: ZBX_SERVER_HOST
      value: zabbix.benpearce.io
    - key: ZBX_REFRESHACTIVECHECKS
      value: 60
