common_users:
  - uid: 2000
    name: woody
    groups: [docker]
  - uid: 2001
    name: borg
    groups: [docker]
common_users_sudoers:
  - user: borg
    runas: root
    commands: /usr/lib/sftp-server
    nopassword: true
common_users_known_hosts:
  - host: github.com
    user: woody
common_users_ssh_config:
  - user: woody
    remote_user: git
    hostname: github.com
    host: github
    identity_file: /home/woody/.ssh/id_ed25519
common_journald_config:
  - option: Storage
    value: volatile
  - option: Compress
    value: 'yes'
  - option: SystemMaxUse
    value: 50M
  - option: SystemMaxFileSize
    value: 5M
  - option: ForwardToSyslog
    value: 'no'
common_docker_compose:
  - repo: git@github.com:ben-pearce/woody-server-deployment.git
    user: woody
    environment:
      - key: HOST
        value: solero.me
      - key: TZ
        value: Europe/London
      - key: PUID
        value: 2000
      - key: PGID
        value: 2000
      - key: CONFIG_DIR
        value: /mnt/data/woody-server-deployment/config
      - key: DATA_DIR
        value: /mnt/data/woody-server-deployment/data
      - key: ZBX_HOSTNAME
        value: woody
      - key: ZBX_SERVER_HOST
        value: zabbix.benpearce.io
      - key: ZBX_REFRESHACTIVECHECKS
        value: 60
