name: üîÑ Private Repository Sync

on:
  schedule:
  - cron: "30 0 * * 1" # Every Monday at 00:30 UTC
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: üõ†Ô∏è Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        
      - name: üõ†Ô∏è Checkout private repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ vars.PRIVATE_REPO }}
          token: ${{ secrets.REPOSITORY_TOKEN }}
          path: private-repo

      - name: üîÑ Sync Private Repository
        run: |
          cp -r ${GITHUB_WORKSPACE}/private-repo/* ./

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git diff | grep -q '\$ANSIBLE_VAULT' && { echo "Aborting: \$ANSIBLE_VAULT found."; exit 1; }
          git add . ':!private-repo'

          if git diff --cached --quiet; then
            echo "Aborting: no changes to commit."
            exit 0
          fi

          git commit -m "chore: üîÑ sync changes from private"
          
          branch="private-sync-$(git rev-parse --short HEAD)"
          git checkout -b $branch
          git push --set-upstream origin $branch

          gh pr create \
            --title "Sync private repository changes" \
            --body "Request to merge changes from private repository with secrets redacted."
        env:
          GH_TOKEN: ${{ github.token }}